#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

# TODO abort if there is no git repo

dir="$HOME/Branches/git-changelog"

for tag in $("$dir/reverse" $(git tag))
do
	if [[ $tag =~ v?[0-9]+(\.[0-9]+)* ]]
	then
		git show $tag | "$dir/parse_tag_object"
	fi
done
