#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

import optparse

def main():
    parser = optparse.OptionParser(usage=, description=)
    parser.add_option("", dest="", type="", default=, help=)

    (options, args) = parser.parse_args()
    del parser


if __name__ == "__main__":
	main()
