#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

import sys
import itertools

def main():
    for line, i in zip(sys.stdin, itertools.count()):
        if line == "-----BEGIN PGP SIGNATURE-----\n":
            sys.exit(0)

        if i >= 4:
            print "\t"+line,
        elif i == 0:
            print line[4:-1]


if __name__ == "__main__":
	main()
